[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "poppler_utils"]

[phases.install]
cmds = [
  "npm install",
  "npm install --prefix server",
  "npm install --prefix client --include=dev"
]
dependsOn = ["setup"]

[phases.build]
cmds = [
  "npm run build --prefix client"
]
dependsOn = ["install"]

[start]
cmd = "node server/index.js"
