// Google Drive — Setlist export
// POST /api/drive/export-setlist
// Finds or creates Productions/ → artist subfolder, then creates a Google Doc.

const express    = require('express');
const router     = express.Router();
const { google } = require('googleapis');
const fs         = require('fs');
const fsp        = require('fs').promises;
const path       = require('path');

const CREDENTIALS_PATH = path.join(__dirname, '../data/gmail-credentials.json');
const TOKEN_PATH       = path.join(__dirname, '../data/gmail-token.json');

function isConfigured() {
  if (process.env.GMAIL_CREDENTIALS && process.env.GMAIL_TOKEN) return true;
  return fs.existsSync(CREDENTIALS_PATH) && fs.existsSync(TOKEN_PATH);
}

function getOAuthClient() {
  const creds = process.env.GMAIL_CREDENTIALS
    ? JSON.parse(process.env.GMAIL_CREDENTIALS)
    : JSON.parse(fs.readFileSync(CREDENTIALS_PATH, 'utf8'));
  const { client_id, client_secret, redirect_uris } = creds.installed || creds.web;
  const client = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);
  const tokens = process.env.GMAIL_TOKEN
    ? JSON.parse(process.env.GMAIL_TOKEN)
    : JSON.parse(fs.readFileSync(TOKEN_PATH, 'utf8'));
  client.setCredentials(tokens);
  client.on('tokens', async (newTokens) => {
    if (process.env.GMAIL_TOKEN) return;
    try {
      const current = JSON.parse(await fsp.readFile(TOKEN_PATH, 'utf8'));
      await fsp.writeFile(TOKEN_PATH, JSON.stringify({ ...current, ...newTokens }, null, 2));
    } catch { /* non-fatal */ }
  });
  return client;
}

// Find a folder by name inside a parent (or root). Returns fileId or null.
async function findFolder(drive, name, parentId) {
  const q = `mimeType='application/vnd.google-apps.folder' and name=${JSON.stringify(name)} and trashed=false`
    + (parentId ? ` and '${parentId}' in parents` : ` and 'root' in parents`);
  const res = await drive.files.list({ q, fields: 'files(id,name)', pageSize: 1 });
  return res.data.files[0]?.id || null;
}

// Find or create a folder. Returns fileId.
async function ensureFolder(drive, name, parentId) {
  const existing = await findFolder(drive, name, parentId);
  if (existing) return existing;
  const res = await drive.files.create({
    requestBody: {
      name,
      mimeType: 'application/vnd.google-apps.folder',
      parents: parentId ? [parentId] : ['root'],
    },
    fields: 'id',
  });
  return res.data.id;
}

// Build Google Docs "batchUpdate" requests from the track list
function buildDocContent(artistName, tracks, totalDuration) {
  // We'll insert plain text — the Docs API inserts at index 1 by default.
  const lines = [];
  lines.push(`Setlist — ${artistName || 'Unknown Artist'}`);
  lines.push(`Total duration: ${totalDuration}`);
  lines.push('');
  lines.push('#   Song                              Artist                  Duration');
  lines.push('─'.repeat(72));
  let n = 0;
  tracks.forEach((t) => {
    if (t.isSeparator) { lines.push('    ' + '·'.repeat(40)); return; }
    const num  = String(++n).padStart(2, ' ');
    const song = (t.songName || '').padEnd(34, ' ').slice(0, 34);
    const art  = (t.artist   || '').padEnd(23, ' ').slice(0, 23);
    const dur  = t.isFound ? (t.durationFormatted || '') : '—';
    lines.push(`${num}  ${song} ${art} ${dur}`);
  });
  lines.push('');
  lines.push(`Generated by Production Hub · ${new Date().toLocaleDateString('he-IL')}`);
  return lines.join('\n');
}

// ── POST /api/drive/export-setlist ───────────────────────────────────────────
router.post('/export-setlist', async (req, res) => {
  if (!isConfigured()) {
    return res.status(503).json({ error: 'Google Drive not configured (no credentials)' });
  }

  const { tracks = [], totalDuration = '', artistName = '', defaultArtist = '' } = req.body || {};
  if (!tracks.length) {
    return res.status(400).json({ error: 'No tracks provided' });
  }

  const folderLabel = (artistName || defaultArtist || 'Setlist').trim();
  const docTitle    = `Setlist — ${folderLabel} — ${new Date().toLocaleDateString('he-IL')}`;

  let auth, drive, docs;
  try {
    auth  = getOAuthClient();
    drive = google.drive({ version: 'v3', auth });
    docs  = google.docs({ version: 'v1', auth });
  } catch (err) {
    console.error('[drive] auth error:', err.message);
    return res.status(500).json({ error: 'Google auth failed: ' + err.message });
  }

  try {
    // 1. Ensure Productions/ root folder
    const productionsId = await ensureFolder(drive, 'Productions', null);

    // 2. Ensure artist subfolder inside Productions/
    const artistFolderId = await ensureFolder(drive, folderLabel, productionsId);

    // 3. Create the Google Doc inside the artist folder
    const createRes = await drive.files.create({
      requestBody: {
        name:     docTitle,
        mimeType: 'application/vnd.google-apps.document',
        parents:  [artistFolderId],
      },
      fields: 'id,webViewLink',
    });
    const docId      = createRes.data.id;
    const docUrl     = createRes.data.webViewLink;

    // 4. Insert content via Docs batchUpdate
    const content = buildDocContent(folderLabel, tracks, totalDuration);
    await docs.documents.batchUpdate({
      documentId: docId,
      requestBody: {
        requests: [
          {
            insertText: {
              location: { index: 1 },
              text: content,
            },
          },
        ],
      },
    });

    return res.json({ url: docUrl });
  } catch (err) {
    console.error('[drive] export error:', err.message);
    return res.status(500).json({ error: err.message });
  }
});

module.exports = router;
